/* eslint-disable max-len */
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import Footer from '@/components/Footer';
import NavBar from '@/components/Navbar';
import { Container } from 'react-bootstrap';
import Providers from './providers';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Dear Sunshine',
  description: 'Generated by ics-software-engineering.github.io',
};

export default function RootLayout({
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const classString = `${inter.className} wrapper`;
  return (
    <html lang="en">
      <body className={classString}>
        <Providers>
          <NavBar />
          <Container>
            <h3>Description</h3>
            <p>Dear Sunshine is a platform where users can write and send uplifting letters to people who need encouragement. The app allows users to connect through anonymous, positive messages. Additionally, users can unlock and send virtual stickers to further brighten someone’s day, creating a supportive, friendly environment.</p>
            <h3>Mockup Pages</h3>
            <p>Home Page: The main page displays featured letters and a call-to-action for users to “Write a Letter” or “Read a Letter.” The page encourages engagement with inspiring quotes or uplifting messages.</p>
            <p>User Profile: Users can create anonymous profiles with minimal personalization options (like a username and avatar colors). This page displays the user’s sent letters, received responses, and earned stickers.</p>
            <p>Message Board: Displays a collection of anonymous letters that users can filter by mood or theme, such as “Encouragement” or “Positive Thoughts.” Users can respond to letters or “Send Sunshine” as a virtual cheer.</p>
            <p>Inbox: An organized page for users to view incoming responses to their letters, sort through replies, and archive conversations.</p>
            <p>Sticker Book: A collection of virtual stickers users can earn by reaching certain goals (e.g., sending five letters) and share with others.</p>
            <p>Mental Help Resources: A page with helpful links and contact information for mental health resources, including helplines and local organizations.</p>
          </Container>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
